// Generated by `contrail connect`. Re-run the command to update; do not edit.
export default {
  contrail: {
    endpoint: "http://127.0.0.1:8787",
    collections: [
      "app.bsky.actor.profile",
      "games.atmo.fours.puzzle",
      "games.atmo.fours.puzzleList",
      "games.atmo.fours.score",
    ],
  },
  generate: {
    files: ["src/lib/contrail/lexicons/source/**/*.json"],
    outdir: "src/lib/contrail/types/",
  },
};
