// Generated by `contrail connect`. Re-run the command to update; do not edit.
import { createPublicServiceClient } from "@atmo-dev/contrail/client";
import type { PublicServiceClientOptions } from "@atmo-dev/contrail/client";
import type {} from "./types/index.js";

export const contrailApi = {
  namespace: "games.atmo",
  serviceMethods: [
    "games.atmo.getCursor",
    "games.atmo.getProfile",
    "games.atmo.notifyOfUpdate",
    "games.atmo.puzzle.getRecord",
    "games.atmo.puzzle.listRecords",
    "games.atmo.puzzleList.getRecord",
    "games.atmo.puzzleList.listRecords",
    "games.atmo.score.getRecord",
    "games.atmo.score.listRecords",
  ],
  protectedMethods: [
    "games.atmo.notifyOfUpdate",
  ],
  collections: [
    "app.bsky.actor.profile",
    "games.atmo.fours.puzzle",
    "games.atmo.fours.puzzleList",
    "games.atmo.fours.score",
  ],
  notifyMethod: "games.atmo.notifyOfUpdate",
} as const;

export const contrailTarget = {
  endpoint: "http://127.0.0.1:8787",
  allowInsecureHttp: true,
  serviceMethods: [
    "games.atmo.getCursor",
    "games.atmo.getProfile",
    "games.atmo.notifyOfUpdate",
    "games.atmo.puzzle.getRecord",
    "games.atmo.puzzle.listRecords",
    "games.atmo.puzzleList.getRecord",
    "games.atmo.puzzleList.listRecords",
    "games.atmo.score.getRecord",
    "games.atmo.score.listRecords",
  ],
  collections: [
    "app.bsky.actor.profile",
    "games.atmo.fours.puzzle",
    "games.atmo.fours.puzzleList",
    "games.atmo.fours.score",
  ],
  notifyMethod: "games.atmo.notifyOfUpdate",
} as const;

export const contrailMethods = contrailTarget.serviceMethods;

export type ContrailTarget = Pick<
  PublicServiceClientOptions,
  "endpoint" | "allowInsecureHttp" | "serviceDid" | "serviceAudience" | "scope" | "protectedMethods" | "serviceMethods" | "collections"
> & {
  notifyMethod?: PublicServiceClientOptions["notifyMethod"] | null;
};

export function createContrailClient(target: ContrailTarget = contrailTarget) {
  const { notifyMethod: targetNotifyMethod, ...runtimeTarget } = target;
  const notifyMethod =
    targetNotifyMethod === undefined
      ? contrailApi.notifyMethod
      : targetNotifyMethod;
  return createPublicServiceClient({
    ...runtimeTarget,
    serviceMethods: target.serviceMethods ?? contrailApi.serviceMethods,
    collections: target.collections ?? contrailApi.collections,
    ...(notifyMethod ? { notifyMethod } : {}),
  });
}

export function createLocalContrailClient(
  endpoint = "http://127.0.0.1:8787",
) {
  return createContrailClient({
    endpoint,
    allowInsecureHttp: true,
    serviceMethods: contrailApi.serviceMethods,
    collections: contrailApi.collections,
    notifyMethod: contrailApi.notifyMethod,
  });
}

export const contrail = createContrailClient();
