// Auto-generated by @atmo-dev/contrail. Do not edit.
// Regenerate with `contrail lexicons generate`.

import _0 from "../../lexicons/custom/games/atmo/fours/puzzle.json";
import _1 from "../../lexicons/custom/games/atmo/fours/puzzleList.json";
import _2 from "../../lexicons/custom/games/atmo/fours/score.json";
import _3 from "../../lexicons/pulled/app/bsky/actor/profile.json";
import _4 from "../../lexicons/pulled/com/atproto/label/defs.json";
import _5 from "../../lexicons/pulled/com/atproto/repo/strongRef.json";
import _6 from "./games/atmo/getCursor.json";
import _7 from "./games/atmo/getProfile.json";
import _8 from "./games/atmo/notifyOfUpdate.json";
import _9 from "./games/atmo/puzzle/getRecord.json";
import _10 from "./games/atmo/puzzle/listRecords.json";
import _11 from "./games/atmo/puzzleList/getRecord.json";
import _12 from "./games/atmo/puzzleList/listRecords.json";
import _13 from "./games/atmo/score/getRecord.json";
import _14 from "./games/atmo/score/listRecords.json";

export const lexicons: object[] = [_0, _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14];
